print("hello world")
b=int(input("enter a number: "))
c=int(input("enter a number: "))
print("addition ",b+c)
print("product :",b*c)
print("int div ",b//c)
print("modulo ",b%c)
print("exponent ",b**c)
print("floating point div ",b/c)